language: clojure
branches:
  only:
    - master
    - 0.4.x
    - element-record
env: DISPLAY=:99.0
before_script: "sh -e /etc/init.d/xvfb start"
notifications:
  recipients:
    - daniel.l.gregoire@gmail.com
